version: '3.8'

services:
  payment-api:
    image: paymentapi_v3:latest
    container_name: paymentapi_v3
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
